dest:
    js: public/js
    css: public/css
    fonts: public/fonts
src:
    css: src/css/*.css
third_party:
    css:
        - node_modules/bootstrap/dist/css/bootstrap.min.css
        - node_modules/font-awesome/css/font-awesome.min.css
    fonts:
        - node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.eot
        - node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.svg
        - node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
        - node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.woff
        - node_modules/font-awesome/fonts/FontAwesome.otf
        - node_modules/font-awesome/fonts/fontawesome-webfont.eot
        - node_modules/font-awesome/fonts/fontawesome-webfont.svg
        - node_modules/font-awesome/fonts/fontawesome-webfont.ttf
        - node_modules/font-awesome/fonts/fontawesome-webfont.woff

